### ISSUE TITLE
Photos aren't passed through the resizer from the new recipe form before upload

### ISSUE THREAD

**Issue by barneyb** [folded-ear/gobrennas-client#101]
The `promiseWellSizedFile` function will ensure that a photo selected for a recipe isn't "too big" to upload. It was on the pathway to the REST api, but doesn't appear to be for the GraphQL API. It (or something equivalent) needs to intercept the selected photo so users don't have to manually resize w/in our arbitrary byte size.

**Comment by switzerb** [comment]
This is done and merged into production.
