### ISSUE TITLE
After saving a recipe w/ a new photo, it doesn't appear on the detail page

### ISSUE THREAD

**Issue by barneyb** [folded-ear/gobrennas-client#102]
After editing a recipe and uploading a new photo, you land back on the recipe detail page with the _old_ photo visible. This is the same behavior as when the recipe save happened via REST, but I expected it to be fixed by mutating via graphql.

**Comment by barneyb** [comment]
The photo saves correctly, it just doesn't make it into the client cache until you force it to update (lib search, refresh app).

**Comment by barneyb** [comment]
This appears to apply to any update except for the title.

**Comment by switzerb** [comment]
Apparently, I did not actually solve the weird caching thing I was seeing.

**Comment by switzerb** [comment]
Done!
