### ISSUE TITLE
close recipe loses search

### ISSUE THREAD

**Issue by barneyb** [folded-ear/gobrennas-client#109]
When you do a search, open a recipe, and then close the recipe, you're brought back to your library _without your prior search_. Using the back button doesn't lose the search, and closing the recipe is "the same" as going back one step.

Exactly how durable the 'active library search' should be is up for debate. Perhaps a machine preference, so navigating to the library always retains the most recent search? I'm not sure if that's weird or not.

Relates to #30.

**Comment by switzerb** [comment]
https://github.com/folded-ear/gobrennas-client/pull/111
