### ISSUE TITLE
Beta environment build fails with invalid argument error

### ISSUE THREAD

**Issue by switzerb** [folded-ear/gobrennas-client#115]
Beta is failing to build and exits with the error:

```
Your build failed to run: generic::invalid_argument: if 'build.service_account' is specified, the build must either (a) specify 'build.logs_bucket', (b) use the REGIONAL_USER_OWNED_BUCKET build.options.default_logs_bucket_behavior option, or (c) use either CLOUD_LOGGING_ONLY / NONE logging options
```

<img width="1288" alt="image" src="https://github.com/folded-ear/gobrennas-client/assets/363095/f88b81d2-4039-4f06-8d57-03e544782fe4">

**Comment by barneyb** [comment]
Needed another option in `cloudbuild.yaml`. API already had it, so it should be good.
